### PR TITLE
Added support for auth

### PR DESCRIPTION
**Pull request by DoriftoShoes**

### CODE REVIEW

**Comment by dzimine** [comment]
LGTM. Count one eye :)

**Comment by enykeev** [comment]
don't we have `st2 auth -t` specifically to avoid using grep and awk in situations like that?

**Comment by DoriftoShoes** [comment]
I guess I don't know how to use `st2 auth -t`...

```
[ root@d0e4fcde4d4f:~ ]$ st2 auth testu -p testp -t
usage: st2 [-h] [--version] [--url BASE_URL] [--auth-url AUTH_URL]
           [--api-url API_URL] [--api-version API_VERSION] [--cacert CACERT]
           [--debug]
           {auth,key,sensor,trigger,rule,action,runner,run,execution,webhook}
           ...
st2: error: unrecognized arguments: -t
[ root@d0e4fcde4d4f:~ ]$ st2 auth -t testu -p testp   
usage: st2 [-h] [--version] [--url BASE_URL] [--auth-url AUTH_URL]
           [--api-url API_URL] [--api-version API_VERSION] [--cacert CACERT]
           [--debug]
           {auth,key,sensor,trigger,rule,action,runner,run,execution,webhook}
           ...
st2: error: unrecognized arguments: -t
[ root@d0e4fcde4d4f:~ ]$ st2 -t auth testu -p testp
usage: st2 [-h] [--version] [--url BASE_URL] [--auth-url AUTH_URL]
           [--api-url API_URL] [--api-version API_VERSION] [--cacert CACERT]
           [--debug]
           {auth,key,sensor,trigger,rule,action,runner,run,execution,webhook}
           ...
st2: error: unrecognized arguments: -t
[ root@d0e4fcde4d4f:~ ]$ st2 auth testu -t -p testp
usage: st2 [-h] [--version] [--url BASE_URL] [--auth-url AUTH_URL]
           [--api-url API_URL] [--api-version API_VERSION] [--cacert CACERT]
           [--debug]
           {auth,key,sensor,trigger,rule,action,runner,run,execution,webhook}
           ...
st2: error: unrecognized arguments: -t
```

**Comment by DoriftoShoes** [comment]
Alrighty then.  I guess that is a newer feature...it wasn't on my 0.8.3 box.  I've tweaked it to use the `-t` option of `auth`

**Comment by Kami** [comment]
Yeah, -t was added to master just recently (soon to be 0.9).

**Pull request merged**
